name: Interacto CI

on:
    push:
      branches:
        - main
      paths-ignore:
        - '**/*.md'
        - '**/*.cff'
        - '.husky'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run package


