name: Interacto CI

on:
    push:
    pull_request:
      branches:
        - main
      paths-ignore:
        - '**/*.md'
        - '**/*.cff'
        - '.husky'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22.18
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run package


